version: "3.9"
services:
  postgres:
    container_name: postgres_container
    image: postgres:15.2
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "root"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "v@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./database/pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres

  server:
    build: ./server
    ports:
      - "5000:5000"
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
